---
name: 'lint'
on:
  push:
  workflow_dispatch:

jobs:
  gofmt:
    steps:
      - name: 'gofmt'
        uses: 'Jerome1337/gofmt-action@v1.0.5'
  markdownlint:
    steps:
      - name: 'markdownlint'
        uses: 'nosborn/github-action-markdown-cli@v3.2.0'
