---
name: 'lint'
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'gofmt'
        uses: 'Jerome1337/gofmt-action@v1.0.5'
      - name: 'markdownlint'
        uses: 'nosborn/github-action-markdown-cli@v3.2.0'
